fragment productEntity on ProductEntity {
  id
  attributes {
    title
    imagePreview {
      data {
        attributes {
          url
          width
          height
          alternativeText
          formats
        }
      }
    }
    price
    rating
    discount
    description
    productTableDescriptions {
      id
      text
      value
    }
  }
}
