fragment productEntity on ProductEntity {
  id
  attributes {
    title
    imagePreview {
      data {
        ...uploadFileEntity
      }
    }
    price
    rating
    discount
    description
    productTableDescriptions {
      id
      text
      value
    }
  }
}
